Repository maestrano/impac-angular, pull requests merged in 2018-05, with the labels that each got.

#520 [IMPAC-834] Invoices List Issues
  src/components/common/transactions-list/transactions-list.component.coffee
  src/components/common/transactions-list/transactions-list.tmpl.html
  src/components/widgets/accounts-cash-projection/accounts-cash-projection.tmpl.html
  src/components/widgets/accounts-invoices-list/accounts-invoices-list.directive.coffee
  src/components/widgets/accounts-invoices-list/accounts-invoices-list.tmpl.html
Labels: bug, review needed

#521 Rework naming
  src/components/common/trends-add/trends-add.component.coffee
  src/components/common/trends-add/trends-add.tmpl.html
  src/components/common/trends-list/trends-list.tmpl.html
  src/components/widgets/accounts-cash-projection/accounts-cash-projection.directive.coffee
Labels: enhancement, review needed

#500 [IMPAC-771]: Cashflow Reconciliation (with bugfix)
  src/components/common/duplicate-transactions-list/duplicate-transactions-list.component.coffee
  src/components/common/duplicate-transactions-list/duplicate-transactions-list.less
  src/components/common/duplicate-transactions-list/duplicate-transactions-list.tmpl.html
  src/components/common/transactions-add/transactions-add.component.coffee
  src/components/common/transactions-list/transactions-list.component.coffee
  src/components/common/transactions-list/transactions-list.tmpl.html
  src/components/widgets/accounts-cash-projection/accounts-cash-projection.directive.coffee
  src/components/widgets/accounts-cash-projection/accounts-cash-projection.tmpl.html
  src/impac-angular.module.js
Labels: enhancement

#517 [IMPAC-668] Chart Threshold Timeperiod Selection
  Changelog.md
  src/components/widgets-common/chart-threshold/chart-threshold.component.coffee
  src/components/widgets-common/chart-threshold/chart-threshold.less
  src/components/widgets-common/chart-threshold/chart-threshold.tmpl.html
  src/components/widgets/accounts-cash-projection/accounts-cash-projection.directive.coffee
  src/locales/en-AU.json
  src/services/highcharts-factory/highcharts-factory.svc.coffee
  src/services/kpis/kpis.svc.coffee
  src/stylesheets/globals.less
Labels: WIP, enhancement

#499 [IMPAC-768] - Allow user to schedule a transaction
  src/components/common/delete-schedule/delete-schedule.component.coffee
  src/components/common/delete-schedule/delete-schedule.less
  src/components/common/delete-schedule/delete-schedule.tmpl.html
  src/components/common/transactions-add/transactions-add.component.coffee
  src/components/common/transactions-add/transactions-add.less
  src/components/common/transactions-add/transactions-add.tmpl.html
  src/components/common/transactions-list/transactions-list.component.coffee
  src/components/common/transactions-list/transactions-list.tmpl.html
  src/components/widgets/accounts-cash-projection/accounts-cash-projection.directive.coffee
  src/components/widgets/accounts-cash-projection/accounts-cash-projection.tmpl.html
  src/impac-angular.module.js
  src/locales/en-AU.json
Labels: WIP, enhancement

#526 [IMPAC-668] Smaller chart-threshold amount input
  src/components/widgets-common/chart-threshold/chart-threshold.less
Labels: bug, review needed

#516 [IMPAC-851] UI updates on "Add transaction" panel
  src/components/common/transactions-add/transactions-add.component.coffee
  src/components/common/transactions-add/transactions-add.less
  src/components/common/transactions-add/transactions-add.tmpl.html
Labels: enhancement

#515 [IMPAC-855] - Include Forecast Payroll img for chart legend
  src/components/widgets-settings/forecast-payroll/forecast-payroll.directive.coffee
  src/components/widgets-settings/forecast-payroll/forecast-payroll.less
  src/images/forecast-payroll.png
  src/services/assets/assets.svc.coffee
Labels: WIP, bug

#528 [IMPAC-771] - Change reconciliation action from PUT to PATCH with custom_action
  Changelog.md
  src/components/common/duplicate-transactions-list/duplicate-transactions-list.tmpl.html
  src/components/widgets/accounts-cash-projection/accounts-cash-projection.directive.coffee
  src/services/bolt-resources/bolt-resources.svc.coffee
Labels: bug, review needed

#527 [IMPAC-850] Add confirm modal for delete transactions & fixes
  src/components/common/delete-schedule/delete-schedule.component.coffee
  src/components/common/delete-schedule/delete-schedule.less
  src/components/common/delete-schedule/delete-schedule.tmpl.html
  src/components/common/delete-widget/delete-widget.component.coffee
  src/components/common/delete-widget/delete-widget.less
  src/components/common/delete-widget/delete-widget.tmpl.html
  src/components/common/transactions-list/transactions-list.component.coffee
  src/components/common/transactions-list/transactions-list.less
  src/components/common/transactions-list/transactions-list.tmpl.html
  src/components/widget/widget.tmpl.html
  src/components/widgets-common/confirm-modal/confirm-modal.component.coffee
  src/components/widgets-common/confirm-modal/confirm-modal.less
  src/components/widgets-common/confirm-modal/confirm-modal.tmpl.html
  src/impac-angular.module.js
  src/locales/en-AU.json
Labels: bug, enhancement

#530 [IMPAC-851]: Rename Customer and Expected payment date
  src/components/common/transactions-add/transactions-add.tmpl.html
Labels: enhancement, review needed

#531 [IMPAC-768]: BugFix for create recurring transactions from real one
  src/components/common/transactions-add/transactions-add.component.coffee
  src/components/common/transactions-list/transactions-list.component.coffee
Labels: bug, review needed

#535 [IMPAC-768]: BugFix to delete transaction and update transaction list
  src/components/common/transactions-list/transactions-list.component.coffee
  src/components/widgets/accounts-cash-projection/accounts-cash-projection.directive.coffee
  src/components/widgets/accounts-cash-projection/accounts-cash-projection.tmpl.html
Labels: bug

#523 [IMPAC-856] Improve formatting of chart xaxis dates
  Changelog.md
  src/services/highcharts-factory/highcharts-factory.svc.coffee
Labels: enhancement

#542 [IMPAC-837] Visualization of trend when adding it
  Changelog.md
  src/components/common/trends-add/trends-add.component.coffee
  src/components/common/trends-add/trends-add.less
  src/components/common/trends-add/trends-add.tmpl.html
  src/components/common/trends-list/trends-list.component.coffee
  src/components/common/trends-list/trends-list.tmpl.html
  src/components/widgets-layouts/custom/accounts-cash-projection/accounts-cash-projection.directive.coffee
  src/components/widgets-layouts/custom/accounts-cash-projection/accounts-cash-projection.tmpl.html
  src/services/highcharts-factory/highcharts-factory.svc.coffee
Labels: enhancement

#522 [IMPAC-868] Implemented improvements on invoices list widget
  Changelog.md
  src/components/common/transactions-list/transactions-list.component.coffee
  src/components/common/transactions-list/transactions-list.less
  src/components/common/transactions-list/transactions-list.tmpl.html
  src/components/widgets-layouts/custom/accounts-cash-projection/accounts-cash-projection.directive.coffee
  src/components/widgets-layouts/custom/accounts-cash-projection/accounts-cash-projection.tmpl.html
  src/components/widgets-layouts/custom/accounts-invoices-list/accounts-invoices-list.directive.coffee
  src/components/widgets-layouts/custom/accounts-invoices-list/accounts-invoices-list.tmpl.html
Labels: enhancement

#543 [IMPAC-838] Group trends
  Changelog.md
  src/components/common/trends-add/trends-add.component.coffee
  src/components/common/trends-add/trends-add.tmpl.html
  src/components/common/trends-list/trends-list.component.coffee
  src/components/common/trends-list/trends-list.less
  src/components/common/trends-list/trends-list.tmpl.html
  src/components/widgets-layouts/custom/accounts-cash-projection/accounts-cash-projection.directive.coffee
  src/components/widgets-layouts/custom/accounts-cash-projection/accounts-cash-projection.tmpl.html
  src/services/widgets/widgets.svc.coffee
Labels: enhancement, review needed

#540 [MARLIN-123] Feature/rec engine 1.0.0
  Changelog.md
  src/components/widgets-layouts/custom/accounts-cash-projection/accounts-cash-projection.directive.coffee
  src/components/widgets-layouts/custom/accounts-cash-projection/accounts-cash-projection.tmpl.html
  src/components/widgets-settings/source-selector/source-selector.directive.coffee
  src/components/widgets-settings/source-selector/source-selector.less
  src/components/widgets-settings/source-selector/source-selector.tmpl.html
  src/impac-angular.module.js
  src/locales/en-AU.json
  src/services/widgets/widgets.svc.coffee
  workspace/index.html
Labels: enhancement

#503 Release v1.8.0
  Changelog.md
  bower.json
  dist/impac-angular.css
  dist/impac-angular.js
  dist/impac-angular.less
  dist/impac-angular.min.css
  dist/impac-angular.min.js
  dist/locales/en-AU.json
  package.json
  src/components/common/transactions-list/transactions-list.component.coffee
  src/components/common/transactions-list/transactions-list.less
  src/components/common/transactions-list/transactions-list.tmpl.html
  src/components/common/trends-add/trends-add.component.coffee
  src/components/common/trends-add/trends-add.less
  src/components/common/trends-add/trends-add.tmpl.html
  src/components/common/trends-list/trends-list.component.coffee
  src/components/common/trends-list/trends-list.less
  src/components/common/trends-list/trends-list.tmpl.html
  src/components/dashboard/dashboard.directive.coffee
  src/components/widget/widget.directive.coffee
  src/components/widgets-common/chart-threshold/chart-threshold.component.coffee
  src/components/widgets-common/info-panel/info-panel.directive.coffee
  src/components/widgets-common/top-buttons/top-buttons.directive.coffee
  src/components/widgets-layouts/custom/accounts-cash-balance/accounts-cash-balance.directive.coffee
  src/components/widgets-layouts/custom/accounts-cash-balance/accounts-cash-balance.less
  src/components/widgets-layouts/custom/accounts-cash-balance/accounts-cash-balance.tmpl.html
  src/components/widgets-layouts/custom/accounts-cash-projection/accounts-cash-projection.directive.coffee
  src/components/widgets-layouts/custom/accounts-cash-projection/accounts-cash-projection.less
  src/components/widgets-layouts/custom/accounts-cash-projection/accounts-cash-projection.tmpl.html
  src/components/widgets-layouts/custom/accounts-invoices-list/accounts-invoices-list.directive.coffee
  src/components/widgets-layouts/custom/accounts-invoices-list/accounts-invoices-list.less
  src/components/widgets-layouts/custom/accounts-invoices-list/accounts-invoices-list.tmpl.html
  src/components/widgets-layouts/table/table.directive.coffee
  src/components/widgets-layouts/table/table.less
  src/components/widgets-layouts/table/table.tmpl.html
  src/components/widgets-settings/hist-mode/hist-mode.directive.coffee
  src/components/widgets-settings/source-selector/source-selector.directive.coffee
  src/components/widgets-settings/source-selector/source-selector.less
  src/components/widgets-settings/source-selector/source-selector.tmpl.html
  src/impac-angular.module.js
  src/locales/en-AU.json
  src/services/dashboards/dashboards.svc.coffee
  src/services/highcharts-factory/highcharts-factory.svc.coffee
  src/services/utilities/utilities.svc.coffee
  src/services/widgets-templates/widgets-templates.svc.coffee
  src/services/widgets/widgets.svc.coffee
  workspace/index.html
Labels: release

#538 [IMPAC-805]: Include the option to enable the TimeSheet modifier
  src/components/widgets-layouts/custom/accounts-cash-projection/accounts-cash-projection.tmpl.html
  src/components/widgets-settings/forecast-payroll/forecast-payroll.directive.coffee
  src/components/widgets-settings/forecast-payroll/forecast-payroll.tmpl.html
  src/components/widgets-settings/payroll/payroll.directive.coffee
  src/components/widgets-settings/payroll/payroll.less
  src/components/widgets-settings/payroll/payroll.tmpl.html
  src/images/payroll.png
  src/impac-angular.module.js
  src/locales/en-AU.json
Labels: enhancement

#545 Release - v1.8.1
  Changelog.md
  bower.json
  dist/impac-angular.css
  dist/impac-angular.js
  dist/impac-angular.less
  dist/impac-angular.min.css
  dist/impac-angular.min.js
  package.json
  src/components/common/transactions-add/transactions-add.component.coffee
  src/components/common/trends-add/trends-add.component.coffee
  src/components/common/trends-add/trends-add.tmpl.html
  src/components/common/trends-list/trends-list.tmpl.html
  src/components/widgets-layouts/custom/accounts-cash-projection/accounts-cash-projection.directive.coffee
  src/components/widgets-settings/source-selector/source-selector.directive.coffee
  src/services/bolt-resources/bolt-resources.svc.coffee
Labels: release
