Repository maestrano/impac-angular, pull requests merged in 2018-06, with the labels that each got.

#553 Release v1.8.2
  Changelog.md
  bower.json
  package.json
  src/components/common/trends-add/trends-add.component.coffee
  src/components/common/trends-add/trends-add.tmpl.html
  src/components/common/trends-list/trends-list.component.coffee
  src/components/widgets-layouts/custom/accounts-cash-projection/accounts-cash-projection.directive.coffee
  src/components/widgets-layouts/custom/accounts-cash-projection/accounts-cash-projection.tmpl.html
Labels: release

#554 Release 1.8.3
  Changelog.md
  bower.json
  dist/impac-angular.css
  dist/impac-angular.js
  dist/impac-angular.less
  dist/impac-angular.min.css
  dist/impac-angular.min.js
  package.json
  src/components/common/trends-add/trends-add.component.coffee
Labels: release

#510 [IMPAC-792] Generic template for table + highstocks layouts
  src/components/dashboard/dashboard.directive.coffee
  src/components/widget/widget.directive.coffee
  src/components/widgets-layouts/components/table-layout/table-layout.component.coffee
  src/components/widgets-layouts/components/table-layout/table-layout.html
  src/components/widgets-layouts/components/table-layout/table-layout.less
  src/components/widgets-layouts/custom-templates/accounts-cash-balance/accounts-cash-balance.directive.coffee
  src/components/widgets-layouts/custom-templates/accounts-cash-balance/accounts-cash-balance.less
  src/components/widgets-layouts/custom-templates/accounts-cash-balance/accounts-cash-balance.tmpl.html
  src/components/widgets-layouts/custom-templates/accounts-cash-projection/accounts-cash-projection.directive.coffee
  src/components/widgets-layouts/custom-templates/accounts-cash-projection/accounts-cash-projection.less
  src/components/widgets-layouts/custom-templates/accounts-cash-projection/accounts-cash-projection.tmpl.html
  src/components/widgets-layouts/generic-templates/table-highstocks/table-highstocks.directive.coffee
  src/components/widgets-layouts/generic-templates/table-highstocks/table-highstocks.less
  src/components/widgets-layouts/generic-templates/table-highstocks/table-highstocks.tmpl.html
  src/components/widgets-layouts/generic-templates/table/table.directive.coffee
  src/components/widgets-layouts/generic-templates/table/table.tmpl.html
  src/components/widgets-layouts/table/table.directive.coffee
  src/components/widgets-layouts/table/table.less
  src/components/widgets-layouts/table/table.tmpl.html
  src/impac-angular.module.js
  src/services/highcharts-factory/highcharts-factory.svc.coffee
  src/services/widgets-templates/widgets-templates.svc.coffee
  src/stylesheets/globals.less
Labels: enhancement

#557 Enable source selector - add company name to source
  src/components/widgets-layouts/custom-templates/accounts-cash-projection/accounts-cash-projection.directive.coffee
  src/components/widgets-settings/source-selector/source-selector.tmpl.html
Labels: enhancement

#562 [IMPAC-865] BugFix - metadata values were changed when the widget was
  src/components/widgets-settings/averages/averages.directive.coffee
Labels: enhancement, review needed

#560 [IMPAC-905] Resolved bug with filtering past due invoices in invoices…
  src/components/widgets-layouts/custom/accounts-invoices-list/accounts-invoices-list.directive.coffee
Labels: enhancement, review needed
