Repository maestrano/impac-angular, pull requests merged in 2018-04, with the labels that each got.

#471 Fixes on Live Balance Widget
  .travis.yml
  Changelog.md
  src/components/common/data-not-found/data-not-found.directive.coffee
  src/components/common/data-not-found/data-not-found.tmpl.html
  src/components/widgets/accounts-live-balance/accounts-live-balance.directive.coffee
  src/components/widgets/accounts-live-balance/accounts-live-balance.tmpl.html
  src/locales/en-AU.json
  src/services/theming/theming.svc.coffee
Labels: bug

#502 Release v1.6.10
  .travis.yml
  Changelog.md
  src/components/common/data-not-found/data-not-found.directive.coffee
  src/components/common/data-not-found/data-not-found.tmpl.html
  src/components/common/transactions-add/transactions-add.component.coffee
  src/components/common/transactions-add/transactions-add.tmpl.html
  src/components/common/transactions-list/transactions-list.component.coffee
  src/components/common/transactions-list/transactions-list.tmpl.html
  src/components/widgets/accounts-cash-projection/accounts-cash-projection.directive.coffee
  src/components/widgets/accounts-cash-projection/accounts-cash-projection.tmpl.html
  src/components/widgets/accounts-invoices-list/accounts-invoices-list.directive.coffee
  src/components/widgets/accounts-invoices-list/accounts-invoices-list.less
  src/components/widgets/accounts-invoices-list/accounts-invoices-list.tmpl.html
  src/components/widgets/accounts-live-balance/accounts-live-balance.directive.coffee
  src/components/widgets/accounts-live-balance/accounts-live-balance.tmpl.html
  src/components/widgets/invoices-list/invoices-list.directive.coffee
  src/impac-angular.module.js
  src/locales/en-AU.json
  src/services/theming/theming.svc.coffee
Labels: release

#504 [IMPAC-811] Add trend in cash projection widget
  src/components/common/trends-add/trends-add.component.coffee
  src/components/common/trends-add/trends-add.less
  src/components/common/trends-add/trends-add.tmpl.html
  src/components/common/trends-list/trends-list.component.coffee
  src/components/common/trends-list/trends-list.less
  src/components/common/trends-list/trends-list.tmpl.html
  src/components/widgets/accounts-cash-projection/accounts-cash-projection.directive.coffee
  src/components/widgets/accounts-cash-projection/accounts-cash-projection.tmpl.html
  src/impac-angular.module.js
Labels: enhancement

#506 [IMPAC-809] - Show the dialog 'Data Not Found' when there is no data in widget
  src/components/widgets/accounts-cash-projection/accounts-cash-projection.directive.coffee
Labels: bug, review needed

#519 [IMPAC-848] Transactions list display bugs
  src/components/common/transactions-list/transactions-list.less
  src/components/common/transactions-list/transactions-list.tmpl.html
Labels: bug, review needed
